language: ruby

script:
  - bundle exec rake travis

before_install:
  # Prevent "Please tell me who you are" errors
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

after_success:
  - bundle exec rake deploy
  
rvm:
  - 2.0.0

env:
  global:
  - secure: "fzg1kaZRs8/Cw7mqWMPbji/h5wQQLdHkyl6jAiJVxB1VctcBa0YixonSUBE2kTbx8oaVOg7cQ1+5O4/5+LrU7h3eHNdzxuaqyPb8swDLPKv3J6vqP3U5fpyYvBN0OXQp42rB6m8X7+VOUGTqTGoNZNLMs85r+CAu5rsVIYIpaQ0="    
